# Generated by Django 5.2.7 on 2025-11-20 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code for the category', max_length=20, unique=True)),
                ('category_type', models.CharField(choices=[('opex', 'Operating Expense'), ('capex', 'Capital Expense'), ('cogs', 'Cost of Goods Sold')], default='opex', help_text='Type of expense category', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'db_table': 'expense_categories',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='expense_cat_code_a581ce_idx'), models.Index(fields=['category_type', 'is_active'], name='expense_cat_categor_b516e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_code', models.CharField(help_text='Unique supplier identifier', max_length=50, unique=True)),
                ('payment_terms_days', models.IntegerField(default=30, help_text='Payment terms in days (default: 30)')),
                ('contact', models.OneToOneField(help_text='Link to contact record (must be of type supplier)', limit_choices_to={'contact_type': 'supplier'}, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_profile', to='core.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suppliers',
                'ordering': ['supplier_code'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_number', models.CharField(help_text='Unique purchase order number', max_length=50, unique=True)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField(help_text='Expected delivery date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total purchase order amount', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(help_text='Currency for this purchase order', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.currency')),
                ('location', models.ForeignKey(help_text='Location where goods/services will be received', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchasing.supplier')),
            ],
            options={
                'db_table': 'purchase_orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(help_text='Unique invoice number', max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total invoice amount', max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid so far', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(help_text='Currency for this invoice', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='core.currency')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Related purchase order (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='purchasing.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='purchasing.supplier')),
            ],
            options={
                'db_table': 'purchase_invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_number', models.CharField(help_text='Unique expense identifier', max_length=50, unique=True)),
                ('expense_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount', max_digits=12)),
                ('description', models.TextField(help_text='Detailed description of the expense')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(help_text='Currency for this expense', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.currency')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='purchasing.expensecategory')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Related purchase order (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='purchasing.purchaseorder')),
                ('supplier', models.ForeignKey(blank=True, help_text='Supplier (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='purchasing.supplier')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description of item/service', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity ordered', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Calculated as quantity * unit_price', max_digits=12)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='purchasing.expensecategory')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_items',
                'indexes': [models.Index(fields=['purchase_order'], name='purchase_or_purchas_a61376_idx'), models.Index(fields=['expense_category'], name='purchase_or_expense_3cecdb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['supplier_code'], name='suppliers_supplie_e2938c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='purchase_or_po_numb_656941_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'order_date'], name='purchase_or_supplie_22a3cb_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='purchase_or_status_5ac239_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['expected_delivery_date'], name='purchase_or_expecte_1b11b9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['invoice_number'], name='purchase_in_invoice_8aefda_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['supplier', 'invoice_date'], name='purchase_in_supplie_8c01fd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['invoice_date'], name='purchase_in_invoice_082ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['due_date'], name='purchase_in_due_dat_a07ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['status'], name='purchase_in_status_64da9d_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_number'], name='expenses_expense_003f04_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'expense_date'], name='expenses_categor_fcbf9c_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['supplier', 'expense_date'], name='expenses_supplie_db3d50_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['location', 'expense_date'], name='expenses_locatio_6285cf_idx'),
        ),
    ]
