# Generated by Django 5.2.7 on 2026-03-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchaseinvoice_base_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_number',
            field=models.CharField(blank=True, help_text='Unique expense identifier (auto-generated if blank)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Unique invoice number (auto-generated if blank)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total invoice amount (base_amount + tax_amount)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, help_text='Unique purchase order number (auto-generated if blank)', max_length=50, unique=True),
        ),
    ]
