# Generated by Django 5.2.7 on 2026-03-07 11:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fix_audit_related_names'),
        ('purchasing', '0005_seed_expense_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapexBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Descriptive name e.g. "New Pattaya Site Fit-Out 2026"', max_length=200)),
                ('total_budget', models.DecimalField(decimal_places=2, help_text='Total approved budget amount', max_digits=15)),
                ('start_date', models.DateField()),
                ('expected_completion_date', models.DateField()),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='planning', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'CAPEX Budget',
                'verbose_name_plural': 'CAPEX Budgets',
                'db_table': 'capex_budgets',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CapexBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgeted_amount', models.DecimalField(decimal_places=2, help_text='Approved budget for this line item', max_digits=15)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'CAPEX Budget Line',
                'verbose_name_plural': 'CAPEX Budget Lines',
                'db_table': 'capex_budget_lines',
                'ordering': ['expense_category__name'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(help_text='First day of the depreciation month (e.g. 2026-01-01)')),
                ('depreciation_amount', models.DecimalField(decimal_places=2, help_text='Depreciation charged for this period', max_digits=12)),
                ('book_value', models.DecimalField(decimal_places=2, help_text='Net book value after applying this entry', max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Depreciation Entry',
                'verbose_name_plural': 'Depreciation Entries',
                'db_table': 'depreciation_entries',
                'ordering': ['asset', 'period_date'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_code', models.CharField(blank=True, help_text='Auto-generated: FA-YYYY-NNN', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Asset description', max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('acquisition_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, help_text='Total cost of acquisition (base amount, excl. tax)', max_digits=15)),
                ('useful_life_months', models.IntegerField(help_text='Expected useful life in months (e.g. 60 = 5 years)')),
                ('residual_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Expected salvage value at end of useful life', max_digits=15)),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('reducing_balance', 'Reducing Balance')], default='straight_line', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disposed', 'Disposed'), ('written_off', 'Written Off')], default='active', max_length=20)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Proceeds received on disposal', max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Fixed Asset',
                'verbose_name_plural': 'Fixed Assets',
                'db_table': 'fixed_assets',
                'ordering': ['asset_code'],
            },
        ),
        migrations.RemoveIndex(
            model_name='expensecategory',
            name='expense_cat_code_a581ce_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_documen_b0da38_idx',
            old_name='expense_doc_type_date_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_status_86293f_idx',
            old_name='expense_status_idx',
        ),
        migrations.RenameIndex(
            model_name='expensesubcategory',
            new_name='expense_sub_categor_0026cf_idx',
            old_name='expense_sub_cat_type_idx',
        ),
        migrations.RenameIndex(
            model_name='expensesubcategory',
            new_name='expense_sub_expense_f7e4dc_idx',
            old_name='expense_sub_type_active_idx',
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Base amount (before tax)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(help_text='Date of the expense or invoice date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_number',
            field=models.CharField(blank=True, help_text='Auto-generated: EXP-YYYY-NNN or INV-YYYY-NNN', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier (optional for plain expenses, usually set for invoices)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='purchasing.supplier'),
        ),
        migrations.AddField(
            model_name='capexbudget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capexbudget',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capex_budgets', to='core.currency'),
        ),
        migrations.AddField(
            model_name='capexbudget',
            name='location',
            field=models.ForeignKey(help_text='Site / location this budget covers', on_delete=django.db.models.deletion.PROTECT, related_name='capex_budgets', to='core.location'),
        ),
        migrations.AddField(
            model_name='capexbudget',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capexbudgetline',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.capexbudget'),
        ),
        migrations.AddField(
            model_name='capexbudgetline',
            name='expense_category',
            field=models.ForeignKey(help_text='Must be a CAPEX-type expense category', limit_choices_to={'category_type': 'capex'}, on_delete=django.db.models.deletion.PROTECT, related_name='capex_budget_lines', to='purchasing.expensecategory'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='acquisition_expense',
            field=models.ForeignKey(blank=True, help_text='Source Expense record (for CAPEX expenses)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='purchasing.expense'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='acquisition_invoice',
            field=models.ForeignKey(blank=True, help_text='Source Purchase Invoice (alternative acquisition source)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='purchasing.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='category',
            field=models.ForeignKey(help_text='Must be a CAPEX-type expense category', limit_choices_to={'category_type': 'capex'}, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='purchasing.expensecategory'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='core.currency'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='core.location'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depreciationentry',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='purchasing.fixedasset'),
        ),
        migrations.AddIndex(
            model_name='capexbudget',
            index=models.Index(fields=['location', 'status'], name='capex_budge_locatio_e21ada_idx'),
        ),
        migrations.AddIndex(
            model_name='capexbudget',
            index=models.Index(fields=['status'], name='capex_budge_status_a52f7d_idx'),
        ),
        migrations.AddIndex(
            model_name='capexbudgetline',
            index=models.Index(fields=['budget', 'expense_category'], name='capex_budge_budget__82106b_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['asset_code'], name='fixed_asset_asset_c_331f99_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['location', 'status'], name='fixed_asset_locatio_99bb32_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['status'], name='fixed_asset_status_a2feec_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['acquisition_date'], name='fixed_asset_acquisi_845f01_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationentry',
            index=models.Index(fields=['asset', 'period_date'], name='depreciatio_asset_i_cee127_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationentry',
            index=models.Index(fields=['period_date'], name='depreciatio_period__44eeb4_idx'),
        ),
        migrations.AddConstraint(
            model_name='depreciationentry',
            constraint=models.UniqueConstraint(fields=('asset', 'period_date'), name='unique_asset_period'),
        ),
    ]
