# Generated by Django 5.2.7 on 2025-11-20 17:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_taxtype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Department name', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Department code (e.g., CULT, SALES, ADMIN)', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this department is currently active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(help_text='Unique employee code', max_length=50, unique=True)),
                ('first_name', models.CharField(help_text='Employee first name', max_length=100)),
                ('last_name', models.CharField(help_text='Employee last name', max_length=100)),
                ('email', models.EmailField(help_text='Employee email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Employee phone number', max_length=20)),
                ('hire_date', models.DateField(help_text='Employee hire date')),
                ('salary', models.DecimalField(decimal_places=2, help_text='Monthly base salary', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this employee is currently active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Employee department', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hr.department')),
                ('location', models.ForeignKey(help_text='Employee location', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, help_text='Associated user account (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['employee_code'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(help_text='Period name (e.g., "2025-01")', max_length=50, unique=True)),
                ('start_date', models.DateField(help_text='Period start date')),
                ('end_date', models.DateField(help_text='Period end date')),
                ('is_closed', models.BooleanField(default=False, help_text='Whether this payroll period is closed')),
            ],
            options={
                'verbose_name_plural': 'Payroll Periods',
                'db_table': 'payroll_periods',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['period_name'], name='payroll_per_period__6c4268_idx'), models.Index(fields=['start_date', 'end_date'], name='payroll_per_start_d_26e3d8_idx'), models.Index(fields=['is_closed'], name='payroll_per_is_clos_c854e7_idx')],
                'constraints': [models.UniqueConstraint(fields=('period_name',), name='unique_payroll_period_name'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_gte_start_date')],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Base salary for this period', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deductions', models.DecimalField(decimal_places=2, default=0, help_text='Total deductions (taxes, benefits, etc.)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_salary', models.DecimalField(decimal_places=2, editable=False, help_text='Net salary (base_salary - deductions) - auto-calculated', max_digits=10)),
                ('payment_date', models.DateField(blank=True, help_text='Date when payment was made', null=True)),
                ('is_paid', models.BooleanField(default=False, help_text='Whether this payroll has been paid')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Employee for this payroll', on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(help_text='Payroll period', on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='hr.payrollperiod')),
            ],
            options={
                'verbose_name_plural': 'Payrolls',
                'db_table': 'payrolls',
                'ordering': ['-period__start_date', 'employee'],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='departments_code_9f933a_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='departments_is_acti_a777bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_department_code'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_code'], name='employees_employe_6fc092_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'is_active'], name='employees_departm_0ef06d_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['location', 'is_active'], name='employees_locatio_e9c12a_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='employees_is_acti_e91717_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('employee_code',), name='unique_employee_code'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee', 'period'], name='payrolls_employe_f60854_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['period', 'is_paid'], name='payrolls_period__d5f14c_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['is_paid'], name='payrolls_is_paid_b5e438_idx'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.UniqueConstraint(fields=('employee', 'period'), name='unique_employee_period'),
        ),
    ]
