# Generated by Django 5.2.7 on 2026-03-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(help_text='Employee email address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, help_text='Unique employee code (auto-generated as EMP-YYYY-NNN if blank)', max_length=50, unique=True),
        ),
    ]
