# Generated by Django 5.2.7 on 2025-11-20 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_taxtype'),
        ('purchasing', '0002_purchaseinvoice_base_amount_and_more'),
        ('sales', '0002_remove_salesinvoice_subtotal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_number', models.CharField(help_text='Unique tax report identifier', max_length=50, unique=True)),
                ('period_start', models.DateField(help_text='Start date of reporting period')),
                ('period_end', models.DateField(help_text='End date of reporting period')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('filed', 'Filed'), ('paid', 'Paid')], default='draft', max_length=50)),
                ('total_vat_payable', models.DecimalField(decimal_places=2, default=0, help_text='Total VAT collected from sales', max_digits=12)),
                ('total_vat_recoverable', models.DecimalField(decimal_places=2, default=0, help_text='Total VAT paid on purchases', max_digits=12)),
                ('net_vat_position', models.DecimalField(decimal_places=2, default=0, help_text='Net VAT position (payable - recoverable). Positive = owe tax, Negative = tax credit', max_digits=12)),
                ('filing_date', models.DateField(blank=True, help_text='Date when report was filed with tax authority', null=True)),
                ('payment_date', models.DateField(blank=True, help_text='Date when tax was paid', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(help_text='Currency for this report', on_delete=django.db.models.deletion.PROTECT, related_name='tax_reports', to='core.currency')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tax_reports',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='TaxJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('payable', 'VAT Payable (Sales)'), ('recoverable', 'VAT Recoverable (Purchase)')], help_text='Type of VAT entry', max_length=50)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Base amount (before tax)', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='Tax amount', max_digits=12)),
                ('entry_date', models.DateField(help_text='Date of the transaction')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_invoice', models.ForeignKey(blank=True, help_text='Source purchase invoice (for recoverable entries)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_entries', to='purchasing.purchaseinvoice')),
                ('sales_invoice', models.ForeignKey(blank=True, help_text='Source sales invoice (for payable entries)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_entries', to='sales.salesinvoice')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='core.taxtype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('tax_report', models.ForeignKey(help_text='Tax report this entry belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='taxes.taxreport')),
            ],
            options={
                'verbose_name': 'Tax Journal Entry',
                'verbose_name_plural': 'Tax Journal Entries',
                'db_table': 'tax_journal_entries',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.AddIndex(
            model_name='taxreport',
            index=models.Index(fields=['report_number'], name='tax_reports_report__0e46f8_idx'),
        ),
        migrations.AddIndex(
            model_name='taxreport',
            index=models.Index(fields=['period_start', 'period_end'], name='tax_reports_period__c93283_idx'),
        ),
        migrations.AddIndex(
            model_name='taxreport',
            index=models.Index(fields=['status'], name='tax_reports_status_f4b5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='taxjournalentry',
            index=models.Index(fields=['tax_report', 'entry_type'], name='tax_journal_tax_rep_97c0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='taxjournalentry',
            index=models.Index(fields=['entry_type', 'entry_date'], name='tax_journal_entry_t_6a70ec_idx'),
        ),
        migrations.AddIndex(
            model_name='taxjournalentry',
            index=models.Index(fields=['sales_invoice'], name='tax_journal_sales_i_e86593_idx'),
        ),
        migrations.AddIndex(
            model_name='taxjournalentry',
            index=models.Index(fields=['purchase_invoice'], name='tax_journal_purchas_b1cb87_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxjournalentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purchase_invoice__isnull', True), ('sales_invoice__isnull', False)), models.Q(('purchase_invoice__isnull', False), ('sales_invoice__isnull', True)), _connector='OR'), name='only_one_invoice_reference'),
        ),
    ]
