# Generated by Django 5.2.7 on 2026-03-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxreport',
            name='report_number',
            field=models.CharField(blank=True, help_text='Unique tax report identifier (auto-generated as TAX-YYYY-MM if blank)', max_length=50, unique=True),
        ),
    ]
