# Generated by Django 5.2.7 on 2025-11-20 17:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_taxtype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostAllocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_date', models.DateField(help_text='The date these allocation rules become effective')),
                ('end_date', models.DateField(blank=True, help_text='The date these rules are no longer effective (null for current)', null=True)),
                ('monthly_capacity_clones', models.IntegerField(default=0, help_text='Monthly production capacity in clones (for overhead allocation)', validators=[django.core.validators.MinValueValidator(0)])),
                ('mother_plant_lifecycle_days', models.IntegerField(default=133, help_text='Expected lifecycle for mother plant (for allocating mother plant costs)')),
                ('expected_clones_per_mother_lifecycle', models.IntegerField(default=0, help_text='Expected total clones from one mother plant over its lifecycle', validators=[django.core.validators.MinValueValidator(0)])),
                ('direct_labor_departments', models.JSONField(default=list, help_text='Department codes that should be allocated as direct labor (e.g., ["CULT"])')),
                ('overhead_labor_departments', models.JSONField(default=list, help_text='Department codes that should be allocated as overhead (e.g., ["ADMIN", "SALES"])')),
                ('cogs_expense_categories', models.JSONField(default=list, help_text='Expense category codes that are COGS (e.g., ["MAT", "NUTR", "SUB"])')),
                ('variable_expense_categories', models.JSONField(default=list, help_text='Expense category codes that are variable OPEX (e.g., ["ELEC", "WATER"])')),
                ('fixed_expense_categories', models.JSONField(default=list, help_text='Expense category codes that are fixed OPEX (e.g., ["RENT", "INS"])')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about these allocation rules')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this allocation rule is currently active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_allocation_rules', to='core.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cost Allocation Rules',
                'db_table': 'cost_allocation_rules',
                'ordering': ['-effective_date', 'location'],
                'indexes': [models.Index(fields=['location', 'effective_date'], name='cost_alloca_locatio_9233ff_idx'), models.Index(fields=['effective_date', 'is_active'], name='cost_alloca_effecti_34de87_idx')],
            },
        ),
        migrations.CreateModel(
            name='CostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(help_text='Date of this cost snapshot')),
                ('period_start', models.DateField(help_text='Start date of the period used for calculations')),
                ('period_end', models.DateField(help_text='End date of the period used for calculations')),
                ('total_clones_produced', models.IntegerField(default=0, help_text='Total clones produced in this period')),
                ('capacity_utilization_pct', models.DecimalField(decimal_places=2, default=0, help_text='Capacity utilization percentage for this period', max_digits=5)),
                ('total_cogs_expenses', models.DecimalField(decimal_places=2, default=0, help_text='Total COGS expenses from Purchasing for this period', max_digits=12)),
                ('total_variable_opex', models.DecimalField(decimal_places=2, default=0, help_text='Total variable OPEX from Purchasing for this period', max_digits=12)),
                ('total_fixed_opex', models.DecimalField(decimal_places=2, default=0, help_text='Total fixed OPEX from Purchasing for this period', max_digits=12)),
                ('total_direct_labor', models.DecimalField(decimal_places=2, default=0, help_text='Total direct labor costs from HR.Payroll for this period', max_digits=12)),
                ('total_overhead_labor', models.DecimalField(decimal_places=2, default=0, help_text='Total overhead labor costs from HR.Payroll for this period', max_digits=12)),
                ('cogs_per_clone', models.DecimalField(decimal_places=2, default=0, help_text='COGS expenses per clone', max_digits=10)),
                ('direct_labor_per_clone', models.DecimalField(decimal_places=2, default=0, help_text='Direct labor per clone', max_digits=10)),
                ('variable_base_per_clone', models.DecimalField(decimal_places=2, default=0, help_text='Variable base cost per clone (COGS + direct labor + variable OPEX)', max_digits=10)),
                ('overhead_per_clone', models.DecimalField(decimal_places=2, default=0, help_text='Overhead per clone (fixed OPEX + overhead labor)', max_digits=10)),
                ('total_cost_per_clone', models.DecimalField(decimal_places=2, default=0, help_text='Total cost per clone (variable base + overhead)', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this snapshot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_snapshots', to='core.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cost Snapshots',
                'db_table': 'cost_snapshots',
                'ordering': ['-snapshot_date', 'location'],
                'indexes': [models.Index(fields=['location', 'snapshot_date'], name='cost_snapsh_locatio_dd2d77_idx'), models.Index(fields=['snapshot_date'], name='cost_snapsh_snapsho_fcb504_idx'), models.Index(fields=['period_start', 'period_end'], name='cost_snapsh_period__825c52_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'snapshot_date'), name='unique_location_snapshot_date')],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier_name', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('bulk', 'Bulk')], help_text='Name of the pricing tier', max_length=50)),
                ('min_quantity', models.IntegerField(default=0, help_text='Minimum quantity for this tier', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_quantity', models.IntegerField(blank=True, help_text='Maximum quantity for this tier (null for unlimited)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_per_clone', models.DecimalField(decimal_places=2, help_text='Price per clone for this tier', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_date', models.DateField(help_text='Date when this pricing tier becomes effective')),
                ('end_date', models.DateField(blank=True, help_text='Date when this pricing tier ends (null for ongoing)', null=True)),
                ('annual_price_increase_pct', models.DecimalField(decimal_places=2, default=0, help_text='Annual price increase percentage (e.g., 5.00 for 5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this pricing tier is currently active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pricing Tiers',
                'db_table': 'pricing_tiers',
                'ordering': ['min_quantity', 'tier_name'],
                'indexes': [models.Index(fields=['tier_name', 'is_active'], name='pricing_tie_tier_na_327789_idx'), models.Index(fields=['effective_date', 'end_date'], name='pricing_tie_effecti_23e8e4_idx'), models.Index(fields=['min_quantity', 'max_quantity'], name='pricing_tie_min_qua_db522b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_quantity__isnull', True), ('max_quantity__gte', models.F('min_quantity')), _connector='OR'), name='max_quantity_gte_min_quantity')],
            },
        ),
    ]
