# Generated by Django 5.2.7 on 2025-10-27 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_currency_alter_location_created_by_and_more'),
        ('genetics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Active_Production', 'Active Production'), ('Recovery', 'Recovery'), ('Low_Production', 'Low Production'), ('Quarantine', 'Quarantine'), ('Retired', 'Retired'), ('Under_Treatment', 'Under Treatment'), ('Growing', 'Growing')], default='active', max_length=50)),
                ('health_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=50)),
                ('cultivation_date', models.DateField(help_text='The date the mother plant was cultivated')),
                ('expected_ready_date', models.DateField(help_text='The expected date the mother plant will be ready for production')),
                ('actual_ready_date', models.DateField(blank=True, help_text='The actual date the mother plant was ready for production', null=True)),
                ('expected_retirement_date', models.DateField(help_text='The expected date the mother plant will be retired')),
                ('actual_retirement_date', models.DateField(blank=True, help_text='The actual date the mother plant was retired', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the mother plant')),
                ('clones_per_cycle_min', models.IntegerField(help_text='The minimum number of clones per cycle')),
                ('clones_per_cycle_max', models.IntegerField(help_text='The maximum number of clones per cycle')),
                ('clones_per_cycle_avg', models.IntegerField(help_text='The default number of clones per cycle')),
                ('total_cycles_year', models.IntegerField(help_text='The total number of cycles per year')),
                ('min_possible_clones_year', models.IntegerField(help_text='The minimum number of clones per year')),
                ('max_possible_clones_year', models.IntegerField(help_text='The maximum number of clones per year')),
                ('avg_clones_year', models.IntegerField(help_text='The default number of clones per year')),
                ('last_cut_date', models.DateField(blank=True, help_text='Auto-updated from latest ProductionBatch', null=True)),
                ('total_cuttings_taken', models.IntegerField(help_text='Lifetime total cuttings')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mother_plants', to='core.location')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genetics.strain')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mother Plants',
                'db_table': 'mother_plants',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('cutting_date', models.DateField()),
                ('expected_rooting_date', models.DateField(help_text='15 days from cutting_date')),
                ('initial_clone_count', models.IntegerField(help_text='Number of cuttings taken')),
                ('rooted_clone_count', models.IntegerField(default=0, help_text='Number that successfully rooted')),
                ('status', models.CharField(choices=[('cutting', 'Cutting Phase'), ('rooting', 'Rooting Phase'), ('completed', 'Completed'), ('failed', 'Failed')], default='cutting', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='core.location')),
                ('mother_plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='cultivation.motherplant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_batches',
                'ordering': ['-cutting_date'],
            },
        ),
        migrations.CreateModel(
            name='Clone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('production_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clones', to='cultivation.productionbatch')),
            ],
            options={
                'db_table': 'clones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='motherplant',
            index=models.Index(fields=['code'], name='mother_plan_code_7ce79f_idx'),
        ),
        migrations.AddIndex(
            model_name='motherplant',
            index=models.Index(fields=['strain'], name='mother_plan_strain__25a21c_idx'),
        ),
        migrations.AddIndex(
            model_name='motherplant',
            index=models.Index(fields=['location'], name='mother_plan_locatio_97a6ac_idx'),
        ),
        migrations.AddIndex(
            model_name='motherplant',
            index=models.Index(fields=['status'], name='mother_plan_status_8cddee_idx'),
        ),
        migrations.AddConstraint(
            model_name='motherplant',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_code'),
        ),
    ]
