# Generated by Django 5.2.7 on 2025-10-27 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0001_initial'),
        ('genetics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clone',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clone',
            name='strain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clones', to='genetics.strain'),
        ),
    ]
