# Generated by Django 5.2.7 on 2025-10-27 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency_alter_location_created_by_and_more'),
        ('cultivation', '0002_clone_name_clone_strain'),
        ('genetics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clone',
            options={'ordering': ['code']},
        ),
        migrations.RemoveField(
            model_name='clone',
            name='name',
        ),
        migrations.RemoveField(
            model_name='clone',
            name='notes',
        ),
        migrations.AddField(
            model_name='clone',
            name='location',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clones', to='core.location'),
        ),
        migrations.AddField(
            model_name='clone',
            name='rooting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clone',
            name='status',
            field=models.CharField(choices=[('cutting', 'Cutting'), ('rooting', 'Rooting'), ('rooted', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('died', 'Died')], default='cutting', max_length=50),
        ),
        migrations.AddField(
            model_name='clone',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='clone',
            name='strain',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clones', to='genetics.strain'),
        ),
        migrations.AddIndex(
            model_name='clone',
            index=models.Index(fields=['status', 'strain', 'location'], name='clones_status_66e025_idx'),
        ),
        migrations.AddIndex(
            model_name='clone',
            index=models.Index(fields=['rooting_date'], name='clones_rooting_fae77d_idx'),
        ),
    ]
