# Generated by Django 5.2.7 on 2025-11-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0003_alter_clone_options_remove_clone_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionbatch',
            name='rooted_clone_count',
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='cost_per_clone',
            field=models.DecimalField(decimal_places=2, default=0, help_text='total_batch_cost / rooted_clone_count', max_digits=10),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='total_batch_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Labor + overhead allocated to this batch', max_digits=12),
        ),
    ]
