# Generated by Django 5.2.7 on 2025-11-20 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact'),
        ('cultivation', '0004_add_batch_costing'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clone',
            name='reserved_for_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.order'),
        ),
        migrations.AddField(
            model_name='clone',
            name='sold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clone',
            name='sold_to_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_clones', to='sales.order'),
        ),
        migrations.CreateModel(
            name='ProductionAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_date', models.DateField(help_text='The date these assumptions become effective')),
                ('mother_plants_count', models.IntegerField(help_text='Number of mother plants')),
                ('clones_per_mother_per_cycle', models.IntegerField(help_text='Number of clones per mother plant per cycle')),
                ('cycle_duration_days', models.IntegerField(help_text='Duration of each production cycle in days')),
                ('survival_rate_pct', models.DecimalField(decimal_places=2, help_text='Survival rate percentage (0.00 to 100.00)', max_digits=5)),
                ('ramp_up_months', models.IntegerField(help_text='Number of months to ramp up to full capacity')),
                ('target_capacity_utilization_pct', models.DecimalField(decimal_places=2, help_text='Target capacity utilization percentage (0.00 to 100.00)', max_digits=5)),
                ('annual_cycles', models.IntegerField(help_text='Number of production cycles per year')),
                ('max_monthly_capacity', models.IntegerField(help_text='Maximum monthly production capacity')),
                ('version', models.IntegerField(default=1, help_text='Version number for tracking assumption changes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_assumptions', to='core.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Production Assumptions',
                'db_table': 'production_assumptions',
                'ordering': ['-effective_date', 'location'],
                'indexes': [models.Index(fields=['location', 'effective_date'], name='production__locatio_4acaf2_idx'), models.Index(fields=['effective_date'], name='production__effecti_cdc80b_idx'), models.Index(fields=['version'], name='production__version_e293f5_idx')],
            },
        ),
    ]
