# Generated by Django 5.2.7 on 2026-03-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0005_clone_reserved_for_order_clone_sold_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherplant',
            name='status',
            field=models.CharField(choices=[('Active_Production', 'Active Production'), ('Recovery', 'Recovery'), ('Low_Production', 'Low Production'), ('Quarantine', 'Quarantine'), ('Retired', 'Retired'), ('Under_Treatment', 'Under Treatment'), ('Growing', 'Growing')], default='Growing', max_length=50),
        ),
        migrations.AlterField(
            model_name='motherplant',
            name='total_cuttings_taken',
            field=models.IntegerField(default=0, help_text='Lifetime total cuttings'),
        ),
    ]
