# Generated by Django 5.2.7 on 2025-11-20 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_currency_alter_location_created_by_and_more'),
        ('cultivation', '0003_alter_clone_options_remove_clone_name_and_more'),
        ('genetics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_date', models.DateField()),
                ('reason', models.CharField(choices=[('died', 'Clone Died'), ('quality_issue', 'Quality Issue - Not Saleable'), ('damaged', 'Physical Damage'), ('contamination', 'Contamination/Disease'), ('theft', 'Theft/Loss'), ('other', 'Other (explain in notes)')], max_length=50)),
                ('notes', models.TextField(help_text='Required: Explain reason for adjustment')),
                ('photo_url', models.URLField(blank=True, help_text='URL to photo documentation (optional)')),
                ('approved_by', models.ForeignKey(help_text='Manager who approved this adjustment', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments_approved', to=settings.AUTH_USER_MODEL)),
                ('clone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='cultivation.clone')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Adjustment',
                'verbose_name_plural': 'Inventory Adjustments',
                'db_table': 'inventory_adjustments',
                'ordering': ['-adjustment_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reorder_point', models.IntegerField(help_text='Alert when available clones fall below this number')),
                ('alert_email', models.EmailField(blank=True, help_text='Email address to notify (optional, uses default if empty)', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alerts', to='core.location')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alerts', to='genetics.strain')),
            ],
            options={
                'verbose_name': 'Inventory Alert',
                'verbose_name_plural': 'Inventory Alerts',
                'db_table': 'inventory_alerts',
                'unique_together': {('strain', 'location')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('production_complete', 'Production Complete - Clone Rooted'), ('transfer', 'Transfer Between Locations'), ('reserved', 'Reserved for Order'), ('sold', 'Sold to Customer'), ('adjustment', 'Manual Adjustment'), ('waste', 'Waste/Died')], max_length=50)),
                ('movement_date', models.DateField()),
                ('reference_type', models.CharField(blank=True, help_text='Type of reference: order, batch, adjustment', max_length=50)),
                ('reference_id', models.CharField(blank=True, help_text='ID of referenced record (order number, batch number, etc.)', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('clone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='cultivation.clone')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(blank=True, help_text='Location clone moved from (null for production)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_out', to='core.location')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_performed', to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(blank=True, help_text='Location clone moved to (null for sale/waste)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_in', to='core.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movements',
                'ordering': ['-movement_date', '-created_at'],
                'indexes': [models.Index(fields=['movement_date', 'movement_type'], name='stock_movem_movemen_c32d8d_idx'), models.Index(fields=['clone', 'movement_date'], name='stock_movem_clone_i_facc65_idx')],
            },
        ),
    ]
