# Generated by Django 5.2.7 on 2025-10-27 10:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Strain Categories',
                'db_table': 'strain_categories',
            },
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The name of the strain', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('catalogue_year', models.IntegerField(help_text='The catalogue year of the strain', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('description', models.TextField(blank=True)),
                ('thc_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='The THC percentage of the strain', max_digits=5, null=True)),
                ('cbd_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='The CBD percentage of the strain', max_digits=5, null=True)),
                ('terpene_profile', models.CharField(blank=True, choices=[('aromatic', 'Aromatic'), ('citrus', 'Citrus'), ('earthy', 'Earthy'), ('floral', 'Floral'), ('herbal', 'Herbal'), ('pine', 'Pine')], help_text='The main terpenes list of the strain', max_length=255)),
                ('breeder', models.TextField(blank=True)),
                ('lineage', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='strains/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genetics.straincategory')),
            ],
            options={
                'verbose_name_plural': 'Strains',
                'db_table': 'strains',
                'ordering': ['slug'],
                'indexes': [models.Index(fields=['slug'], name='strains_slug_eb4fb9_idx'), models.Index(fields=['catalogue_year'], name='strains_catalog_7c37de_idx'), models.Index(fields=['category'], name='strains_categor_7f99b0_idx'), models.Index(fields=['is_active'], name='strains_is_acti_ea53f2_idx')],
            },
        ),
    ]
