# Generated by Django 5.2.7 on 2026-01-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genetics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='terpene_profile',
            field=models.CharField(blank=True, help_text='Comma-separated list of terpenes (e.g., Myrcene, Limonene, Caryophyllene)', max_length=255),
        ),
    ]
