# Generated by Django 5.2.7 on 2026-03-06 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genetics', '0002_alter_strain_terpene_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='cbd_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The CBD percentage of the strain (0–100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='strain',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if blank)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='thc_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The THC percentage of the strain (0–100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
