# Generated by Django 5.2.7 on 2025-11-20 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_contact'),
        ('genetics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_code', models.CharField(help_text='Unique customer identifier', max_length=50, unique=True)),
                ('tier', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('bulk', 'Bulk')], default='retail', help_text='Customer pricing tier', max_length=50)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Maximum credit allowed', max_digits=12)),
                ('payment_terms_days', models.IntegerField(default=0, help_text='Payment terms in days (0 = immediate)')),
                ('contact', models.OneToOneField(help_text='Link to contact record (must be of type customer)', limit_choices_to={'contact_type': 'customer'}, on_delete=django.db.models.deletion.PROTECT, related_name='customer_profile', to='core.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['customer_code'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(help_text='Unique order identifier', max_length=50, unique=True)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_production', 'In Production'), ('ready', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total order amount', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.customer')),
                ('location', models.ForeignKey(help_text='Location where order will be fulfilled', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_note_number', models.CharField(help_text='Unique delivery note identifier', max_length=50, unique=True)),
                ('delivery_date', models.DateField(help_text='Actual delivery date')),
                ('delivered_by', models.CharField(blank=True, help_text='Person who delivered the order', max_length=200)),
                ('received_by', models.CharField(blank=True, help_text='Person who received the order', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('partially_delivered', 'Partially Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Delivery notes or special instructions')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('delivery_location', models.ForeignKey(help_text='Location where delivery occurred', on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Order being delivered', on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='sales.order')),
            ],
            options={
                'db_table': 'delivery_notes',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Number of clones ordered')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per clone', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Calculated as quantity * unit_price', max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='sales.order')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='genetics.strain')),
            ],
            options={
                'db_table': 'order_lines',
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delivered', models.IntegerField(help_text='Actual quantity delivered')),
                ('notes', models.TextField(blank=True, help_text='Notes about this specific line item')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_lines', to='sales.deliverynote')),
                ('order_line', models.ForeignKey(help_text='Reference to original order line', on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='sales.orderline')),
            ],
            options={
                'db_table': 'delivery_note_lines',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('bulk', 'Bulk')], help_text='Customer tier this price applies to', max_length=50)),
                ('price_per_clone', models.DecimalField(decimal_places=2, help_text='Price per clone for this strain and tier', max_digits=10)),
                ('min_quantity', models.IntegerField(default=1, help_text='Minimum order quantity for this price')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='core.currency')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='genetics.strain')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'price_lists',
                'ordering': ['strain', 'tier'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(help_text='Unique invoice identifier', max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Total before tax', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total including tax', max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid so far', max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('delivery_note', models.ForeignKey(blank=True, help_text='Delivery note this invoice is based on (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.deliverynote')),
                ('order', models.ForeignKey(help_text='Order this invoice is for', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.order')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_number', models.CharField(help_text='Unique payment identifier', max_length=50, unique=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('credit_card', 'Credit Card'), ('other', 'Other')], max_length=50)),
                ('reference_number', models.CharField(blank=True, help_text='Bank reference, check number, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.salesinvoice')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_code'], name='customers_custome_fdedee_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tier'], name='customers_tier_094047_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_order_n_1336be_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'order_date'], name='orders_custome_9fba8b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['expected_delivery_date'], name='orders_expecte_4311c5_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverynote',
            index=models.Index(fields=['delivery_note_number'], name='delivery_no_deliver_900b35_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverynote',
            index=models.Index(fields=['order'], name='delivery_no_order_i_04e1c2_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverynote',
            index=models.Index(fields=['delivery_date'], name='delivery_no_deliver_891b56_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverynote',
            index=models.Index(fields=['status'], name='delivery_no_status_525961_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['order', 'strain'], name='order_lines_order_i_156eab_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverynoteline',
            index=models.Index(fields=['delivery_note', 'order_line'], name='delivery_no_deliver_8a6bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['strain', 'tier', 'is_active'], name='price_lists_strain__bed125_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('strain', 'tier'), name='unique_strain_tier'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['invoice_number'], name='sales_invoi_invoice_3ac144_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['order'], name='sales_invoi_order_i_c53508_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['invoice_date'], name='sales_invoi_invoice_dd4721_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['due_date'], name='sales_invoi_due_dat_07e1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['status'], name='sales_invoi_status_463950_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_number'], name='payments_payment_c27a96_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='payments_invoice_9dd568_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_payment_aebcb7_idx'),
        ),
    ]
