# Generated by Django 5.2.7 on 2025-11-20 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_taxtype'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base amount before tax', max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='tax_type',
            field=models.ForeignKey(blank=True, help_text='Tax type applied (e.g., VAT 7%)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='core.taxtype'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax amount calculated from base_amount and tax_type', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total including tax (base_amount + tax_amount)', max_digits=12),
        ),
    ]
