# Generated by Django 5.2.7 on 2026-03-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_salesinvoice_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, help_text='Unique customer identifier (auto-generated if blank)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='delivery_note_number',
            field=models.CharField(blank=True, help_text='Unique delivery note identifier (auto-generated if blank)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, help_text='Unique order identifier (auto-generated if blank)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_production', 'In Production'), ('ready', 'Ready for Delivery'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(blank=True, help_text='Unique payment identifier (auto-generated if blank)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Unique invoice identifier (auto-generated if blank)', max_length=50, unique=True),
        ),
    ]
