# Generated by Django 5.2.7 on 2026-03-06 15:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_taxtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxtype',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Tax rate as a percentage (e.g. 7.00 for 7%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
